# Generated by Django 5.1.6 on 2025-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='is_reasonable',
            new_name='is_satisfactory',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='proposed_settlement',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('End User', 'End User'), ('Admin', 'Admin'), ('AI Engineer', 'AI Engineer'), ('Staff', 'Staff')], default='End User', max_length=50),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
